<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />
      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Areas\Admin\Data\" />
      <Folder Include="Areas\Admin\Models\" />
      <Folder Include="Areas\Admin\Pages\" />
      <Folder Include="wwwroot\AdminTemplate\app-assets\" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\feather2467.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\feather2467.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\feather2467.ttf" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\feather2467.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb.ttf" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb.woff2" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_Bold.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_Bold.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_Bold.ttf" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_Bold.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_Bold.woff2" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_Light.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_Light.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_Light.ttf" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_Light.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_Light.woff2" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_Medium.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_Medium.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_Medium.ttf" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_Medium.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_Medium.woff2" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_UltraLight.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_UltraLight.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_UltraLight.ttf" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_UltraLight.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\fonts\IRANSansWeb_UltraLight.woff2" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\feather\style.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\font-awesome\css\font-awesome.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb.ttf" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb.woff2" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_Bold.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_Bold.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_Bold.ttf" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_Bold.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_Bold.woff2" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_Light.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_Light.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_Light.ttf" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_Light.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_Light.woff2" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_Medium.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_Medium.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_Medium.ttf" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_Medium.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_Medium.woff2" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_UltraLight.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_UltraLight.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_UltraLight.ttf" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_UltraLight.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\IRANSansWeb_UltraLight.woff2" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\meteocons\fonts\meteoconsddea.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\meteocons\fonts\meteoconsddea.ttf" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\meteocons\style.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\simple-line-icons\fonts\Simple-Line-Icons.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\simple-line-icons\fonts\Simple-Line-Icons.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\simple-line-icons\fonts\Simple-Line-Icons.ttf" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\simple-line-icons\fonts\Simple-Line-Iconsd41d.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\fonts\simple-line-icons\style.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\flags\br.png" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\flags\de.png" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\flags\es.png" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\flags\us.png" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\1.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\10.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\11.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\12.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\14.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\16.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\17.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\18.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\19.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\2.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\20.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\21.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\22.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\23.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\24.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\25.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\26.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\27.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\28.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\29.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\3.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\30.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\31.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\32.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\33.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\4.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\5.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\6.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\7.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\8.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\gallery\9.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\ico\apple-icon-120.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\ico\apple-icon-152.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\ico\apple-icon-60.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\ico\apple-icon-76.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\ico\favicon-32.png" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\logo.png" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\logos\logo-big-black.png" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\logos\logo-color-big.png" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\pages\sativa.png" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\pages\signature-scan.png" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\photos\01.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\photos\02.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\photos\03.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\photos\04.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\photos\05.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\photos\1.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\photos\14.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\photos\15.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\photos\16.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\photos\17.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\photos\2.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\photos\3.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\photos\4.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\photos\5.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\photos\7.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\photos\8.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portfolio\portfolio-1.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portfolio\portfolio-2.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portfolio\portfolio-3.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portfolio\portfolio-4.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portfolio\portfolio-5.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portfolio\portfolio-6.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\medium\avatar-m-9.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-1.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-11.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-12.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-14.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-15.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-16.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-17.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-18.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-19.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-20.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-21.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-22.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-23.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-24.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-27.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-3.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-4.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-5.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-6.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-7.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-8.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\portrait\small\avatar-s-9.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\sidebar-bg\01.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\sidebar-bg\02.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\sidebar-bg\03.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\sidebar-bg\04.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\sidebar-bg\05.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\sidebar-bg\06.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\sidebar-bg\07.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\sidebar-bg\08.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\tour\cross.png" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\img\width-600\portfolio-14.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\chartist.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\dragula.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\dropzone.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_AMS-Regular-2.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_AMS-Regular-3.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_AMS-Regular-4.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_AMS-Regular.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Caligraphic-Bold-2.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Caligraphic-Bold-3.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Caligraphic-Bold.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Caligraphic-Bold.ttf" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Caligraphic-Regular-2.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Caligraphic-Regular-3.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Caligraphic-Regular.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Caligraphic-Regular.woff2" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Fraktur-Bold-2.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Fraktur-Bold-3.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Fraktur-Bold-4.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Fraktur-Bold.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Fraktur-Regular-2.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Fraktur-Regular-3.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Fraktur-Regular-4.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Fraktur-Regular.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Main-Bold-2.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Main-Bold-3.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Main-Bold-4.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Main-Bold.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Main-Italic-2.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Main-Italic-3.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Main-Italic-4.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Main-Italic.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Main-Regular-2.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Main-Regular-3.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Main-Regular.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Main-Regular.woff2" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Math-Italic-2.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Math-Italic-3.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Math-Italic.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Math-Italic.woff2" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_SansSerif-Regular-2.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_SansSerif-Regular-3.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_SansSerif-Regular-4.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_SansSerif-Regular.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Script-Regular-2.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Script-Regular-3.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Script-Regular-4.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Script-Regular.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Size1-Regular-2.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Size1-Regular-3.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Size1-Regular-4.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Size1-Regular.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Size2-Regular-2.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Size2-Regular-3.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Size2-Regular-4.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Size2-Regular.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Size3-Regular-2.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Size3-Regular-3.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Size3-Regular.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Size3-Regular.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Size4-Regular-2.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Size4-Regular-3.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Size4-Regular-4.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Size4-Regular.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Typewriter-Regular-2.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Typewriter-Regular-3.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Typewriter-Regular-4.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fonts\KaTeX_Typewriter-Regular.html" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\fullcalendar.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\hopscotch.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\katex.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\monokai-sublime.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\perfect-scrollbar.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\pickadate\pickadate.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\prism.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\quill.bubble.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\quill.snow.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\raty\fonts\raty.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\raty\fonts\raty.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\raty\fonts\raty.ttf" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\raty\fonts\raty.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\raty\fonts\ratyd41d.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\raty\jquery.raty.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\sweetalert2.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\switchery.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\tables\datatable\datatables.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\tables\datatable\responsive.dataTables.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\tagging.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\toastr.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\css\wizard.css" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\chart.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\chartist.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\core\bootstrap.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\core\jquery-3.3.1.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\core\popper.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\datatable\buttons.flash.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\datatable\buttons.html5.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\datatable\buttons.print.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\datatable\dataTables.buttons.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\datatable\datatables.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\datatable\dataTables.responsive.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\datatable\jszip.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\datatable\pdfmake.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\datatable\vfs_fonts.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\dragula.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\dropzone.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\fullcalendar.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\gmaps.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\highlight.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\hopscotch.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\jqBootstrapValidation.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\jquery-ui.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\jquery.countdown.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\jquery.matchHeight-min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\jquery.raty.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\jquery.steps.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\jquery.validate.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\katex.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\moment.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\pace\pace.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\perfect-scrollbar.jquery.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\pickadate\legacy.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\pickadate\picker.date.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\pickadate\picker.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\pickadate\picker.time.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\prism.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\quill.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\screenfull.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\sweetalert2.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\switchery.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\tagging.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\toastr.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\typeahead\bloodhound.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\typeahead\handlebars.js" />
      <_ContentIncludedByDefault Remove="wwwroot\AdminTemplate\vendors\js\typeahead\typeahead.bundle.min.js" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Store.Persistence\Store.Persistence.csproj" />
    </ItemGroup>

</Project>
